
version: 2

models:
  - name: jobindsats_subjects
    description: ""
    columns:
      - name: SubjectID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
